name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 6 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Default metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Tokyo
          filename: /photos/github-metrics.*
          extras_css: |
                title {
                  color: #39C5BB;
                }
                h1 {
                  color: #39C5BB;
                }
                h2 {
                  color: #39C5BB;
                }
